version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chromavision-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - chromavision-network

  api:
    build:
      context: .
      dockerfile: ChromaVision.API/Dockerfile
    container_name: chromavision-api
    depends_on:
      - db
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ChromaVisionDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    networks:
      - chromavision-network

networks:
  chromavision-network:
    driver: bridge

volumes:
  sqlserver-data: